name: Deploy master
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          caches: "npm"

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' src/\*

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Vessanseinalta
          environment_name: Vessanseinalta-env
          version_label: vessanseinalta-${{ github.run_number }}-${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
          existing_bucket_name: vessanseinalta-be
